### PR TITLE
travis: fix PHP 7.0 build

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by enumag** [comment]
Thanks, I guess I should check the other packages for this.

**Comment by TomasVotruba** [comment]
Good idea, if tests are failing

**Comment by enumag** [comment]
All the other non-deprecated packages are fine. :-)

**Comment by TomasVotruba** [comment]
Great :)

**Pull request merged**
